services:
  mentor_swagger:
    container_name: mentor_swagger
    build:
      context: ./swagger
      dockerfile: Dockerfile
    env_file: ./swagger/.env
    ports:
      - "9000:9000"
    networks:
      - network_name
    # Только если нужно live-обновление кода:
    volumes:
      - ./swagger:/app
      - swagger_data:/data
      
    command: >
      uvicorn main:app 
      --host 0.0.0.0 
      --port 9000 
      --reload

volumes:
  swagger_data:

networks:
  network_name:
    driver: bridge
