services:
  mentor_swagger:
    container_name: mentor_swagger
    build:
      context: ./swagger
      dockerfile: Dockerfile
    env_file: ./swagger/.env
    ports:
      - "9000:9000"
    networks:
      - mentor_network
    # Только если нужно live-обновление кода:
    volumes:
      - ./swagger:/app
      - swagger_data:/data
      - /etc/letsencrypt/live/stlthwl.pro:/etc/letsencrypt/live/stlthwl.pro:ro
      - /etc/letsencrypt/archive/stlthwl.pro:/etc/letsencrypt/archive/stlthwl.pro:ro
      
    command: >
      uvicorn main:app 
      --host 0.0.0.0 
      --port 9000 
      --reload
      --ssl-keyfile /etc/letsencrypt/live/stlthwl.pro/privkey.pem
      --ssl-certfile /etc/letsencrypt/live/stlthwl.pro/fullchain.pem
      --ssl-version 2

volumes:
  swagger_data:

networks:
  mentor_network:
    external: true
